/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.betterjavacode.eurekawebclient;

import org.junit.jupiter.api.Test;

import com.betterjavacode.eurekawebclient.EurekawebclientApplication;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        EurekawebclientApplication classUnderTest = new EurekawebclientApplication();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
