/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.betterjavacode.eurekaserver;

import org.junit.jupiter.api.Test;

import com.betterjavacode.productservice.EurekaclientApplication;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        EurekaclientApplication classUnderTest = new EurekaclientApplication();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
