/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.betterjavacode.eurekaserver;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        EurekaserverApplication classUnderTest = new EurekaserverApplication();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
